### ISSUE TITLE
Propuesta App Mobile para Android en React Native

### ISSUE THREAD

**Issue by agusvazquez** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#100]
Hola como estan?

Propongo la realizacion de una mobile app en react native que sea exactamente igual al frontend que vamos a armar. Creo que esta es la unica manera  en la que voy a poder ayudar al proyecto. Pero tampoco quiero complicarles la vida, todos sabemos que la web es prioridad 1.

Habiendo dicho esto:

-  Quieren que cree una app mobile con los mocks que figuran en la pagina? 
- Al no ser muchas pantallas creo que lo podria llegar a hacer yo solo, de todas maneras cualquier tipo de ayuda es bienvenida.
- Se va a usar? porque si los fiscales no lo necesitan no tiene sentido que armemos algo que no se va a usar.
- Tendria que ser solo en android, porque iOS no la va a aprobar ya que es una app de uso interno y lleva otro procedimiento.
- Puedo aportar mi store personal para subirla (como ni lo uso, hasta puedo cambiarle el nombre a la libertad avanza).

El stack que propongo seria usar 
- [React Native](https://reactnative.dev/)
- [React Native Elements (UI)](https://reactnativeelements.com/)
- [React Navigation](https://reactnavigation.org/)
- [Sentry para capturar issues (mejora).](https://docs.sentry.io/platforms/react-native/)

**Comment by pablobazan** [comment]
acá con experiencia en Android nativo y Flutter si quieren hacer una versión nativa

**Comment by agusvazquez** [comment]
https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/pull/104

**Comment by fermelone** [comment]
@agusvazquez entiendo el tema de las aprobaciones de cada store, android y iOS, pero no se puede hacer una version que corra en browser como hacen los hoteles? asi no dejamos a la gente de iOS afuera. Ejemplo: https://appmecm.majestic-resorts.com/
esa web la podes extraer a una "app" que no deja de ser un container si vas a share > add to home screen.

**Comment by agusvazquez** [comment]
El tema es que esto seria una app mobile nativa, que es muy distinto a lo que seria una web. No funcionan igual, de hecho internamente funciona como una native app.

Para los iOS users tendriamos la plataforma web que se esta armando en nextjs. Quizas podemos tirar el lance a que iOS la apruebe, no creo que nos cueste mucho, de todas maneras lo mas probable es que la rechazen.

**Comment by moyakpo** [comment]
Por el corto tiempo que hay creo que la mejor opción va a ser que el front sea web, ademas pensemos en la diversidad de dispositivos que vayan a usarse, no va a hacer tiempo para testear apps nativas,

**Comment by agusvazquez** [comment]
Dale dale, cero drama! Tratare de ayudar con el testing / arreglo de bugs en el front web.

Se que nextJS es bastante parecido a React pero aun asi nunca lo use.

**Comment by moyakpo** [comment]
Next es todo un framework que usa React para el render. Te recomiendo ver los tutoriales de Fazt Web en youtube, explica muy bien algunos conceptos como el caso de Next.

**Comment by agusvazquez** [comment]
Gracias! :)

**Comment by agusvazquez** [comment]
Cierro porque no se va a hacer
