### ISSUE TITLE
Frontend: Libreria de componentes para tailwind

### ISSUE THREAD

**Issue by franmerlini** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#124]
Dado que de momento se estan haciendo todos los componentes 100% con clases de tailwind, propongo usar alguna libreria de componentes de tailwind que agilize el desarrollo del front y nos permita estandarizar estilos y customizarlos de manera mas eficiente.

Razones por las que considero necesario utilizar una libreria de componentes:

- **Consistencia y eficiencia**: Una libreria de componentes de componentes permiten un diseño coherente en aplicaciones o sitios web. Al utilizar elementos prediseñados y probados, se elimina la necesidad de repetir el trabajo de diseño. Esta estructura evita duplicar tareas cada vez que se demande una función similar.Esto ahorra tiempo y esfuerzo, y además asegura que el resultado final sea coherente.
- **Reutilización**: Al crear una librería de componentes, es posible reutilizar los mismos elementos de diseño en varios proyectos. Esto es especialmente útil para empresas o diseñadores que gestionan numerosos proyectos al mismo tiempo y necesitan asegurarse de que los elementos están "unificados" en cuanto a forma y funcionalidad sea cual sea el proyecto en el que se utilicen.
- **Mejora de la calidad**: Una librería de componentes permite realizar pruebas exhaustivas y depuración en cada uno de los elementos. Esto garantiza tanto un buen diseño como un funcionamiento eficaz, evitando los errores típicos.
- **Escalabilidad**: A medida que un proyecto crece, es esencial.

**Comment by shartrooper** [comment]
HeadlessUI es una bastante adecuada para toda una gama de widgets, basado en tailwind. [LINK](https://headlessui.com/)

**Comment by BrunoMPedraza** [comment]
Un enfoque muy robusto sería TDD con Storybook en la creación de módulos, pero considero que el tiempo anula cualquiera de estas ideas.

**Comment by gabrielchapov** [comment]
Recomiendo [https://ui.shadcn.com/](url), la estoy usando en el laburo y me gusta bastante, escalable y con buenas opciones de accesibilidad

**Comment by IsidoroAros** [comment]
Cree un mini pr configurando preline que es la que vengo usando en el laburo, recomiendo que echen un ojo https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/pull/187
https://preline.co/docs/index.html

**Comment by jdimodugno** [comment]
También es posible utilizar [Next UI](https://nextui.org), es muy potable

**Comment by Luis-Fernando-Molina** [comment]
> Cree un mini pr configurando preline que es la que vengo usando en el laburo, recomiendo que echen un ojo #187 https://preline.co/docs/index.html

Parece que ese PR no prospero, cierro este caso.
