### ISSUE TITLE
Arquitectura Del Sistema - Opinion / Dudas 

### ISSUE THREAD

**Issue by marcopoggi** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#135]
Buenas, creo que deberiamos **clarificar un poco la arquitectura** general del sistema que se quiere lograr, con el objetivo de entender e interpretar mejor lo que se requiere.
Tal vez muchas personas quieren empezar a colaborar pero no entienden como o en que exactamente.
Realice el siguiente diagrama(**_boceto rapido)_** para clarificar esto, basandome en el **README** y en las funcionalidades principales:

![Screenshot from 2023-10-29 00-36-59](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/71911407/c9f62d15-3b17-4731-b7cf-db87195e50fb)

Obviamente se puede mejorar o pasar en limpio, pero es para ver si la mano va por ahi.
Quedo abierto a aclaraciones si no entendi algo en particular o si surge alguna duda/debate sobre esto. :+1:

**Comment by Luis-Fernando-Molina** [comment]
Tu diagrama es una buena interpretacion del README. Ahora, no estoy seguro que lo que se viene implementando sea tal cual, no he tenido tiempo de revisarlo. Pudieras ver si es asi lo que se ha implentado hasta hoy, hacer los ajustes y luego agregar tu diagrama al README?
