### ISSUE TITLE
Definir los contratos de los servicios requeridos siguiendo un estándar

### ISSUE THREAD

**Issue by matricali** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#137]
Sugiero definir los contratos de los servicios requeridos por la aplicación bajo la especificacion OpenAPI 3 (OAS)
Lo ideal sería poder avanzar con esta documentación de forma temprana de forma que haya una alineación previa e idealmente total entre quienes estan desarrollando el front y el back.

**Comment by Luis-Fernando-Molina** [comment]
Parece muy buena idea.

**Comment by matricali** [comment]
@Luis-Fernando-Molina veo que se comenzó a trabajar de esta forma posterior a la creación de este ticket, en un PR sin descripcion
https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/pull/71

No me termina de quedar claro si hay una alineación previa en la construccion de este documento entre FrontEnd y Backend

Pero en principio entiendo se podría cerrar este ticket dado que lo que se está sugiriendo ya se está aplicando.
