### ISSUE TITLE
[API] Renombrar endpoints a ingles

### ISSUE THREAD

**Issue by juanem1** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#170]
Actualmente tenemos una mezcla entre ingles y español (por ejemplo `/user` y `/mesa`)

Tendriamos que renombrar los endpoints a ingles de la siguiente manera:
- mesa        -> `table` o `voting-table`
- fiscalizar  -> `audit`
- denuncia -> `complaint`

**Comment by alelnro1** [comment]
PR creado: https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/pull/173

**Comment by Luis-Fernando-Molina** [comment]
Ademas, eso habilita a que se sumen developers de todo el mundo.

**Comment by Facundo-Wehrli** [comment]
Se podría crear un README en inglés también

**Comment by Facundo-Wehrli** [comment]
> Ademas, eso habilita a que se sumen developers de todo el mundo.

Se podría crear un README en inglés también

**Comment by Luis-Fernando-Molina** [comment]
> > Ademas, eso habilita a que se sumen developers de todo el mundo.
> 
> Se podría crear un README en inglés también
De hecho estaria necesitando eso, porque pienso invitar a todos los desarrolladores del mundo con un Tweet en Ingles, pero luego de que tengamos un README en ingles. Podes hacerlo, aunque sea con ChatGPT?

**Comment by Facundo-Wehrli** [comment]
> > > Ademas, eso habilita a que se sumen developers de todo el mundo.
> > 
> > 
> > Se podría crear un README en inglés también
> > De hecho estaria necesitando eso, porque pienso invitar a todos los desarrolladores del mundo con un Tweet en Ingles, pero luego de que tengamos un README en ingles. Podes hacerlo, aunque sea con ChatGPT?
Yo lo hago, entre hoy y mañana:
podría dejar el README en español pero tener el que está en inglés arriba y arriba de todo un link que te lleve a la parte en la que se encuentra la documentación en español?, me explico? Sería README en inglés y debajo el README en español. Si alguien se le ocurre otra cosa comente.

**Comment by Facundo-Wehrli** [comment]
Se me ocurrió crear otro README para desarrolladores anglosajones y renombrar ambos readmes  quedarían: 
README_EN.md
README_ES.md

**Comment by Facundo-Wehrli** [comment]
> Se me ocurrió crear otro README para desarrolladores anglosajones y renombrar ambos readmes quedarían: README_EN.md README_ES.md

Sabiendo que github solo muestra el que es nombrado como README.md dejaré con ese nombre al README que estará en inglés y el que quiera ver el readme en español deberá entrar al README_ES.md.

**Comment by Facundo-Wehrli** [comment]
PR creado: https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/pull/194
