### ISSUE TITLE
si no existe user proteger las rutas

### ISSUE THREAD

**Issue by mauriciocruzdeveloper** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#198]
Agregué un useEffect en routes que mire si hay usuario y si no hay, me redirija a login.

**Comment by matricali** [comment]
Relacionado a #199 

La información bien podria estar directamente en el PR,  no hay necesidad de mantener tambien en simultaneo el issue (sobre todo porque no estaban relacionados)

**Comment by mauriciocruzdeveloper** [comment]
> Relacionado a #199
> 
> La información bien podria estar directamente en el PR, no hay necesidad de mantener tambien en simultaneo el issue (sobre todo porque no estaban relacionados)

Cierro el issue entonces!
