### ISSUE TITLE
Añadir donaciones a README.md

### ISSUE THREAD

**Issue by ivanmmurciaua** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#57]
Hey, gran proyecto.

¿Habéis pensado en ofrecer direcciones públicas de blockchain (BTC [LN incluida], USDT, USDC, ETH etc...) para recibir donaciones de tod@ el/la que quiera contribuir y no sepa de código?

Sería un gran modo de fondear el proyecto, generando transparencia y haciendo cada movimiento auditable por el resto del mundo.

Esto generaría _engagement_ con tod@s l@s posibles devs de Argentina dando el impulso que se necesita antes del 19.

Además se podría crear un tablero kanban o scrum en cualquier plataforma de colaboración para ver el avance del proyecto, y a modo de retribución poner _bounties_ por cada _task_ a cumplir.

Un saludo desde 🇪🇸 y a por todas 🦁⚡

**Comment by fermelone** [comment]
**Mi punto de vista:** No se debería permitir ninguna donación. Es para bardo. Se van a meter a pedir guita en nombre del proyecto, pueden acusarlo de scam y que en realidad era todo para "sacarle guita a la gente", etc. Cuanto menos material le demos a los que estan en contra de esto, mejor.

**Comment by matricali** [comment]
No me parece ni que haga falta, ni que sea correcto pedir donaciones para este proyecto. No lo veo ni cercano a ser una prioridad.
Y tal como comenta @fermelone , considero que daria mas complicaciones que beneficios.

**Comment by ivanmmurciaua** [comment]
Hey, gracias por la opinión.

Bajo mi punto de vista sería interesante **analizar** un modelo de retribución justa para l@s desarrollador@s, me parece genial que lo hagan por principios, si es así adelante y chapeau por ustedes.

Mi propuesta de hacerlo con crypto venía de la mano de la auditablidad de esos fondos, si el mundo entero puede auditar este movimiento y contribuir a él, puede ser el inicio de algo revolucionario, y Argentina es un país muy avanzado en cuanto a crypto se refiere.

En cuanto a "acusarlo de SCAM", no deberían si no crean su propio token, podrían simplemente cobrar en stablecoins o BTC. Están apoyando un proyecto político de pura libertad económica, creo que crear un sistema para conseguir unas elecciones limpias debería tener una recompensa monetaria más allá de la heroica de "salvar la nación".

Dicho esto, es una opinión desde España, ustedes deciden como quieren afrontar este reto. Sea como sea, todo el apoyo desde el otro lado del charco en esta epopeya.

Un saludo!

**Comment by fermelone** [comment]
@ivanmmurciaua muchas gracias por la oferta, pero creo que por ahora no nos interesa, la opinion al respecto es bastante unanime. Por favor, procede a cerrar este issue para que no haya confusiones. Gracias.
