### ISSUE TITLE
[BE] Propuesta / dudas

### ISSUE THREAD

**Issue by Mystogab** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#67]
Hola podría dar una mano con el backend pero no me parece muy prudente usar un framework (nestjs) para complicar las cosas si están cortos de tiempo, si quieren alguna parte hecha en NodeJS sin frameworks locos (solo una api por ejemplo con fastify o express) puedo ofrecer mi ayuda o en algún modulo, a todo esto tampoco se bien donde estará montada la infraestructura si sera serverless o donde lo piensan montar.

En fin un abrazo y gracias por su esfuerzo, y ya saben si puedo dar una mano con backend/infra tengo 8 añitos como BE con nodejs y entornos serverless.
Animos que falta poco para que todo termine, abrazo!

**Comment by ppsirg** [comment]
ya hay una definicion para usar el framework nestjs, si estas en contra por favor ve directo al issue relacionado y expone tu caso https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/issues/16

**Comment by Luis-Fernando-Molina** [comment]
Cierro este Issue porque parece que la discusion del tema se dio en otro lado.
