### ISSUE TITLE
BACKEND: Hola! Ya tengo una parte hecha del backend.

### ISSUE THREAD

**Issue by tomasbarak** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#70]
Me gustaria poder subirla (a main u otra branch). Puedo unirme como colaborador? Gracias!

**Comment by juanFernigrini** [comment]
En que la tienen echa? y sobre que db?

**Comment by ppsirg** [comment]
no es este el repo para el backend? https://github.com/Las-Fuerzas-Del-Cielo/api

cuenta por favor:
- que stack de tecnologias usas
- que arquitectura implementas 
- que funcionalidades implementaste
- que despliegue requiere

puedes usar gists para ir mostrando partes

**Comment by juanFernigrini** [comment]
Pero esta vacio... por eso no avance en nada, pero tengo para montar un spring rápidamente. 
 Con web security
 Jwtoken

Habia pensado unas cosas pero no abren discord

**Comment by fferrin** [comment]
Pongan las discusiones sobre el back en este ticket https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/issues/16. Una vez que lo hagan cierren este ticket así no interfiere con los issues de las funcionalidades.

Para mostrar lo que hicieron pueden hacer un fork del repo y hacer los cambios ahí. No lo hagan en gists porque no es tan fácil de revisar como en un repositorio.

Tengan en cuenta también que antes de hacer algo lo tienen que consultar para ver que nadie esté haciendo lo mismo y que eso sea lo que efectivamente se quiere implementar, así no gastan tiempo en cosas que finalmente no se terminen incorporando.

**Comment by fermelone** [comment]
@tomasbarak es necesario tener este issue abierto? sino por favor cerralo. Gracias!
