### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by fabioetorres** [Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral#74]
Hola, En que puedo ayudar. Para lo que pueda hacer estoy a disposición del Proyecto. Neuquén Capital. Horarios amplios para ayudarlos.
Saludos

**Comment by fferrin** [comment]
Podes ver el estado de las cosas en el server de [Discord](https://discord.gg/fPrW8yAf). Una vez que te unas cerrá este issue para que no interfiera en los issues de las funcionalidades

**Comment by fabioetorres** [comment]
YA acepte la invitacion y registrado para ayudar!
